name: Rust CI

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: 1.86.0

      - name: Install cargo-nextest
        uses: taiki-e/install-action@9d936bb31f5a2c91dbb07ed40f861659f6478b9f
        with:
          tool: cargo-nextest

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@054db53350805f83040bf3e6e9b8cf5a139aa7c9

      - name: Run Clippy
        run: cargo clippy --all-targets -- -W clippy::pedantic -W clippy::nursery -D warnings

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Tests
        run: cargo nextest run
